name: ci

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: latest  # Use the latest version
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Prepare Environment
        run: |
          pnpm install --no-frozen-lockfile || pnpm install --no-frozen-lockfile  # Retry logic
      - name: Build Project
        run: |
          pnpm run build || pnpm run build  # Retry logic
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./example/dist
          keep_files: true  # 保留之前构建的文件
